# Generated by Django 3.2.9 on 2023-10-13 13:51

import agendaFinanceira.models
import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendaFinanceira', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldoinicial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Enviado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='despesa',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=agendaFinanceira.models.upload_to_despesa, validators=[core.helpers.validate_file_extension], verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='saldoinicial',
            name='banco',
            field=models.CharField(choices=[('SANTANDER', 'SANTANDER'), ('BRADESCO', 'BRADESCO'), ('ITAU', 'ITAU'), ('CAIXA', 'CAIXA'), ('BANCO DO BRASIL', 'BANCO DO BRASIL'), ('PICPAY', 'PICPAY'), ('MERCADO PAGO', 'MERCADO PAGO'), ('SAFRA PAY', 'SAFRA PAY')], max_length=100, verbose_name='Nome do Banco'),
        ),
        migrations.AlterField(
            model_name='saldoinicial',
            name='data_inicial',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='SaldoAtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('SANTANDER', 'SANTANDER'), ('BRADESCO', 'BRADESCO'), ('ITAU', 'ITAU'), ('CAIXA', 'CAIXA'), ('BANCO DO BRASIL', 'BANCO DO BRASIL'), ('PICPAY', 'PICPAY'), ('MERCADO PAGO', 'MERCADO PAGO'), ('SAFRA PAY', 'SAFRA PAY')], max_length=100, verbose_name='Nome do Banco')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Atual')),
                ('data_atual', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
