# Generated by Django 3.2.9 on 2023-10-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendaFinanceira', '0003_auto_20231013_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldoatual',
            old_name='saldo',
            new_name='saldo_atual',
        ),
    ]
