# Generated by Django 3.2.9 on 2023-10-13 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendaFinanceira', '0004_rename_saldo_saldoatual_saldo_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldoatual',
            name='date_modificacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da Transação'),
            preserve_default=False,
        ),
    ]
