# Generated by Django 3.2.9 on 2023-10-10 18:48

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import prestadores.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_especialidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrestadorPessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando Validação'), ('VALIDADO', 'Validado (Ativo)'), ('INVALIDO', 'Inválido'), ('INATIVO', 'Inativo')], default='PENDENTE', max_length=30)),
                ('cd_prestador', models.IntegerField(blank=True, null=True)),
                ('nm_prestador', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('nr_cpf_cgc', models.CharField(max_length=11, validators=[core.helpers.validate_CPF], verbose_name='CPF')),
                ('dt_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('ds_email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('nr_cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('ds_endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço')),
                ('ds_complemento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Complemento')),
                ('ds_bairro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bairro')),
                ('nm_cidade', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cidade')),
                ('cd_uf', models.CharField(blank=True, max_length=200, null=True, verbose_name='UF')),
                ('nr_fone_contato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone para Contato')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_insercao', models.DateTimeField(auto_now_add=True)),
                ('identidade_frente', models.FileField(blank=True, null=True, upload_to=prestadores.models.identidade_frente_directory_path, validators=[core.helpers.validate_file_extension], verbose_name='Documento')),
                ('especialidades', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='prestadores.especialidade')),
            ],
        ),
    ]
